version: '3.8'

services:
  app:
    image: muhammetaydin/dockerdemoapril:0.0.1
    ports:
      - 8080:8080
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/localspringbootdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      -SLEEP_LENGTH: 5
    depends_on:
      db:
        condition: service_completed_successfully
  db:
    image: muhammetaydin/mysql
    environment:
        DATABASE_HOST: docker-mysql
        DATABASE_PORT: 3306
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: localspringbootdb
        MYSQL_USER: admin
        MYSQL_PASSWORD: root
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
